# Advanced Workflow Example
# Shows all available configuration options

name: E2E Tests - Advanced

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # Run nightly at 2 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    name: Run Playwright Tests with Full Configuration
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=json > test-results.json
        continue-on-error: true
        env:
          CI: true

      - name: Analyze test failures with full configuration
        if: failure()
        uses: decision-crafters/playwright-failure-analyzer@v1
        with:
          # Required
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Report configuration
          report-path: 'test-results.json'
          max-failures: 10  # Include up to 10 failures

          # Issue configuration
          issue-title: '🚨 E2E Test Failures - ${{ github.ref_name }} - Run #${{ github.run_number }}'
          issue-labels: 'bug,e2e,playwright,priority-high,automated'
          assignees: 'qa-team,dev-lead'  # Assign to specific users

          # Behavior
          deduplicate: true  # Prevent duplicate issues (default)
          ai-analysis: true  # Enable AI analysis

        env:
          # AI Configuration (Optional - using cheapest option)
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          AI_MODEL: 'openrouter/deepseek/deepseek-chat'

      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
          retention-days: 30

      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ E2E tests failed on this PR. Check the workflow logs for details.'
            })
