# Basic Workflow Example
# This is the simplest way to use the Playwright Failure Analyzer

name: E2E Tests - Basic

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Required for creating issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test --reporter=json > test-results.json
        continue-on-error: true  # Don't fail workflow on test failures

      - name: Analyze test failures
        if: failure()  # Only run if tests failed
        uses: decision-crafters/playwright-failure-analyzer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          report-path: 'test-results.json'
