name: Auto-update Pre-commit Hooks

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    name: Update Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Update pre-commit hooks
        id: update
        run: |
          # Capture the current state
          cp .pre-commit-config.yaml .pre-commit-config.yaml.old

          # Update hooks to latest versions
          pre-commit autoupdate

          # Check if there were any changes
          if diff -q .pre-commit-config.yaml .pre-commit-config.yaml.old > /dev/null; then
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "No updates available"
          else
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "Updates found!"

            # Show what changed
            echo "### Changes:"
            diff .pre-commit-config.yaml.old .pre-commit-config.yaml || true
          fi

          # Cleanup
          rm .pre-commit-config.yaml.old

      - name: Run pre-commit on all files
        if: steps.update.outputs.updated == 'true'
        run: |
          pre-commit run --all-files || true
        continue-on-error: true

      - name: Create Pull Request
        if: steps.update.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update pre-commit hooks to latest versions'
          title: '🔄 Auto-update: Pre-commit Hooks'
          body: |
            ## 🔄 Automated Pre-commit Hooks Update

            This PR updates pre-commit hooks to their latest versions.

            ### 📋 What Changed

            The following hooks were updated:
            - Check the diff in `.pre-commit-config.yaml` for details

            ### ✅ Verification Steps

            1. **Review the changes** in `.pre-commit-config.yaml`
            2. **Test locally**:
               ```bash
               pre-commit run --all-files
               ```
            3. **Check for any new requirements** or breaking changes in hook documentation
            4. **Merge** if everything looks good

            ### 📚 Resources

            - [Pre-commit Documentation](https://pre-commit.com/)
            - [Project Pre-commit Setup](docs/PRE_COMMIT_SETUP.md)

            ### 🤖 Automation

            This PR was automatically created by the `auto-update-precommit` workflow.
            - **Schedule**: Weekly (Monday 9:00 AM UTC)
            - **Manual trigger**: [Run workflow](../../actions/workflows/auto-update-precommit.yml)

            ---
            *Generated by GitHub Actions - Workflow: `auto-update-precommit.yml`*
          branch: automated/update-precommit-hooks
          delete-branch: true
          labels: |
            dependencies
            automated
            pre-commit

      - name: Summary
        run: |
          if [ "${{ steps.update.outputs.updated }}" == "true" ]; then
            echo "✅ Pre-commit hooks updated! PR created for review."
          else
            echo "ℹ️ No updates available. All hooks are up to date."
          fi
